### ISSUE TITLE
Toss em at a roof... yuh dun goof'd. 

### ISSUE THREAD

**Issue by Leejit** [XFuryMCPE/EnderPearls#2]
A sure way to die, no lie. Give it a try. 
Take a TeleBall (is what I call em) and toss it at the roof.  oh sh!!... ur dying now. oops.

**Comment by XFuryMCPE** [comment]
Cannot reproduce.

**Comment by Leejit** [comment]
eh, ill delete my cheat protection and see if that changes it. you cheat blocker is obv different. 

but yeah, this has killed many of my players. surprised it doesn't do same for you.
